export const theme = {
  colors: {
    primary: '#1A1A1A',
    secondary: '#B8860B',
    background: '#F8F9FA',
    white: '#FFFFFF',
    text: '#1A1A1A',
    textSecondary: '#666',
    textMuted: '#888',
    placeholder: '#A0A0A0',
    border: '#EFEFEF',
    borderLight: '#F0F0F0',
    cardShadow: '#000',
    favorite: '#FF4444',
    ratingBg: '#FFF9E6',
    buttonBg: '#FFFFFF',
    buttonActiveBg: '#1A1A1A',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 15,
    lg: 20,
    xl: 25,
    xxl: 30,
  },
  borderRadius: {
    sm: 12,
    md: 15,
    lg: 20,
    xl: 24,
    round: 20,
    pill: 20,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 20,
    xl: 22,
    xxl: 28,
  },
  fontWeight: {
    normal: 'normal',
    medium: '600',
    bold: 'bold',
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 15,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 5,
    },
    heart: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 3,
    },
  },
};